on:
  push:
    branches:
      - pipeline-experimental  # Adjust the branch as needed
  pull_request:
    branches:
      - pipeline-experimental   # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'
          
      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2.2.1

      - name: Build and test
        run: mvn test
