name: Web Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_web_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'

      # Other setup steps if required

      - name: Run Web Tests
        run: |
          cd src/test/java/saucedemo/web
          mvn test
