on:
  push:
    branches:
      - main  # Adjust the branch as needed
  pull_request:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Chrome
        run: |
         VERSION_STRING="114.0.5735.198-1 "
          wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${VERSION_STRING}_amd64.deb"
          sudo dpkg -i "google-chrome-stable_${VERSION_STRING}_amd64.deb"

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2.2.1
        with:
          chromedriver-version: '114.0.5735.90'

      - name: Start Appium Server
        run: |
          # Add commands to start Appium server here
          # Example: appium &

      - name: Build and test
        run: mvn test
